import Link from "next/link"
import Head from "next/head"
import Image from "next/image"
import style from "../../styles/Catalog.module.scss"

export default function Catalog( {productsList} ) {
    return(
        <div className="1">
            <Head>
                <title>Каталог</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div className={style.category}>
                
            </div>
            <div className={style.products}>
                {productsList.lenght !== 0 ? (
                    productsList.map((product) => (
                        <div className={style.cart} key={product.id}>
                            <div className={style.image}>
                                <Image 
                                    src={product.image} 
                                    alt={product.name} 
                                    width={200}
                                    height={300}
                                />
                            </div>
                            <p className={style.name}>
                                {product.name}
                             </p>
                             <span className={style.desc}>
                                {product.desc}
                             </span>
                             <p className={style.price}>
                                {product.price}
                             </p>
                        </div>
                    ))
                ) : (
                    <div>Товары не найдены ...</div>
                )}
            </div>
        </div>
    )
}

export async function getStaticProps() {
    const res = await fetch('http://localhost:3000//api/catalogList');
    const productsList = await res.json();

    if(!productsList) {
        return{
            notFound: true,
        };
    }

    return{
        props: {
            productsList,
        },
    };
}

/*
export async function getStaticPaths() {
    const res = await fetch('http://localhost:3000//api/catalogList');
    const products = await res.json();

    const paths = products.map((product) => ({
        params: {id: product.id},
    }));

    return{ 
        paths, 
        fallback: true,
    }
} */