import Link from "next/link";
import Head from "next/head";
import Image from "next/image";
import style from '../../../styles/Product.module.scss'

export default function Product( {content} ) {
    const product = content[0];
    return(
        <div className={style.wrapper}>
            <Head>
                <title>{product.name}</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Link href={`/catalog/${product.category}`}>
                <button className={style.backBut}>Назад</button>
            </Link>
            <div className={style.content}>
                <div className={style.cart}>
                    <p className={style.name}>
                        {product.name}
                    </p>
                    <div className={style.image}>
                        <Image 
                            src={product.image} 
                            alt={product.name} 
                            width={200}
                            height={300}
                        />
                    </div>
                    <div className={style.sizes}>
                        <p>Доступные размеры:</p>
                        <ul>
                            {product.sizes.map((e, i) => (
                                <li key={i}>
                                    {e}
                                </li>
                            ))}
                        </ul>
                    </div>
                    <span className={style.desc}>
                        {product.desc}
                    </span>
                    <p className={style.price}>
                        {product.price}
                    </p>
                </div>
            </div>
        </div>
    )
}

export async function getStaticProps(context) {
    const content = await fetch(`http://localhost:3000/api/products/${context.params.id}`)
        .then((res) => res.json());
    
    if (!content) {
        return {
            notFound: true,
        }
    }
    return{
        props: {
            content,
        },
    };
}

export async function getStaticPaths() {
    const products = await fetch('http://localhost:3000/api/products')
        .then((res) => res.json());

    const paths = products.map((product) => ({
        params:
            {
                category: product.category,
                id: product.id,
            }
    }));

    return{ 
        paths, 
        fallback: false,
    }
}