import Link from "next/link";
import Head from "next/head";
import style from '../../../styles/Product.module.scss'
import ProductCard from "../../../components/ProductCard";

export default function Product( {content} ) {
    const product = content[0];
    return(
        <>
            <Head>
                <title>{product.name}</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Link href={`/catalog/${product.category}`}>
                <button className={style.backBut}>Назад</button>
            </Link>
            <ProductCard product={product} />
        </>
    )
}

export async function getStaticProps(context) {
    const content = await fetch(`http://localhost:3000/api/products/${context.params.id}`)
        .then((res) => res.json());
    
    if (!content) {
        return {
            notFound: true,
        }
    }
    return{
        props: {
            content,
        },
    };
}

export async function getStaticPaths() {
    const products = await fetch('http://localhost:3000/api/products')
        .then((res) => res.json());

    const paths = products.map((product) => ({
        params:
            {
                category: product.category,
                id: product.id,
            }
    }));

    return{ 
        paths, 
        fallback: false,
    }
}