import Head from "next/head"
import Image from "next/image"
import style from "../styles/About.module.scss"

export default function About( {posts} ) {
    return(
        <div className="1">
            <Head>
                <title>О компании</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className={style.advantages}>
                {posts.lenght !== 0 ? (
                    posts.map((post) => ( 
                        (post.name == 'base') ? 
                        (<div key={post.id} className={style.post}>
                            <div className={style.container}>
                                <div className={style.name}>
                                    <p>{post.head}</p>
                                </div>
                                <div className={style.description}>
                                    <p>{post.desc}</p>
                                </div>
                            </div>
                        </div> ) :

                        (<div key={post.id} className={post.name == 'postLeft' ?
                            style.postLeft: style.postRight}>
                            <div className={style.image}>
                                <Image
                                    src={post.image}
                                    alt={post.head}
                                    layout='fill'
                                />
                            </div>
                            <div className={style.container}>
                                <div className={style.name}>
                                    <p>{post.head}</p>
                                </div>
                                <div className={style.description}>
                                    <p>{post.desc}</p>
                                </div>
                            </div>
                        </div>)
                    ))
                ): (
                    <div> Ошибка, попробуйте позже</div>
                )}
            </div>
        </div>
    )
}

export async function getStaticProps() {
    const res = await fetch('http://localhost:3000//api/aboutPosts');
    const posts = await res.json();

    if(!posts) {
        return{
            notFound: true,
        };
    }

    return{
        props: {
            posts,
        },
    };
}