import Head from "next/head"
import Image from "next/image"
import { useEffect, useState, useRef } from "react"
import style from "../styles/About.module.scss"
import {CSSTransition} from 'react-transition-group'

export default function About({ posts }) {
    return(
        <>
            <Head>
                <title>О компании - почему нам доверяют</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <PostsWrapper posts={posts} />
        </>
    )
}

const PostsWrapper = ({ posts }) => {
    return(
        <div className={style.advantages}>
            {posts.lenght !== 0 ? (
                posts.map((post) => (
                    <LazyPost key={post.id}>
                        <Post data={post} />
                    </LazyPost>
                ))
            ): (
                <div> Ошибка, попробуйте позже</div>
            )}
        </div>
    )
}


const LazyPost = ({ children }) => {
    const [isIntersecting, setIntersecting] = useState(false);

    const boxRef = useRef(null);
    const options = {
        rootMargin: '0px',
        threshold: 0.6,
    }

    useEffect(() => {
        const post = boxRef.current;

        const observer = new IntersectionObserver((entries, observer) => {
            entries.forEach(entry => {
                if (entry.isIntersecting) {
                    setIntersecting(true);
                    observer.unobserve(entry.target)
                }
            })
        }, options);

        observer.observe(post);

        return () => observer.unobserve(post);
    }, [])

    return(
        <div ref={boxRef} className={style.postBox}>
            {!isIntersecting ? <Placeholder /> : children}
        </div>
    )
}

const Post = ({ data }) => {
    const postRef = useRef(null);
    const [start, setStart] = useState(false);
    
    const postAnimationDotsR = {
        enter: style.postEnterR,
        enterActive: style.postEnterRActive,
    };

    const postAnimationDotsL = {
        enter: style.postEnterL,
        enterActive: style.postEnterLActive,
    };

    useEffect(() => {
        setStart(true);
    }, [])
    
    return(
        <CSSTransition 
            in={start}
            nodeRef={postRef}
            classNames={(data.id % 2) == 0 ? postAnimationDotsL : postAnimationDotsR}
            timeout={1600}
            mountOnEnter
        > 
            <div 
                ref={postRef} 
                key={data.id} 
                className={(data.id % 2) == 0 ?
                    style.post : `${style.post} ${style.left}`}>
                {data.id != '1' ? (<div className={style.image}>
                    <Image
                        src={data.image}
                        alt={data.head}
                        layout='fill'
                    />
                </div>) : null}
                <div className={style.data}>
                    <div className={style.name}>
                        <p>{data.head}</p>
                    </div>
                    <div className={style.description}>
                        <p>{data.desc}</p>
                    </div>
                </div>
            </div>
        </CSSTransition> 
    )
}

const Placeholder = ({}) => {
    return( 
        <div className={style.placeHolder}>
        </div>
    )
};


export async function getStaticProps() {
    const res = await fetch('http://localhost:3000//api/aboutPosts');
    const posts = await res.json();

    if(!posts) {
        return{
            notFound: true,
        };
    }

    return{
        props: {
            posts,
        },
    };
}
/*
const props = [
    'Временные строительные двери: надежность и безопасность на всех этапах проекта!

    Наши временные строительные двери представляют собой идеальное решение для строительных проектов, ремонта или реконструкции зданий. Они были специально разработаны, чтобы обеспечить вашему объекту безопасность, защиту и комфорт на протяжении всего времени проведения работ.
    
    Преимущества наших временных строительных дверей:
    
    1. Надежность: Мы предлагаем только высококачественные двери, которые изготовлены из прочных материалов, обеспечивающих длительный срок службы. Наша продукция соответствует самым строгим строительным стандартам, чтобы вы могли быть уверены в ее надежности.
    
    2. Безопасность: Временные строительные двери имеют встроенные механизмы защиты, предотвращающие несанкционированный доступ и вандализм. Они оснащены надежными замками и усиленными конструкциями, чтобы обеспечить защиту вашего объекта от кражи и повреждений.
    
    3. Удобство использования: Наши временные строительные двери легко открываются и закрываются, что обеспечивает удобство при проходе рабочих, поставщиков и посетителей. Они также оснащены специальными механизмами для облегчения грузоподъемности, что делает их идеальным выбором для транспортировки материалов и оборудования.
    
    4. Гибкость и адаптивность: Временные строительные двери легко устанавливаются и демонтируются, что делает их идеальным решением для проектов различного масштаба. Мы предлагаем широкий выбор размеров и конфигураций дверей, чтобы точно соответствовать вашим потребностям.
    
    Не компрометируйте безопасность и комфорт на вашей строительной площадке. Выберите наши временные строительные двери и обеспечьте надежность своего проекта. Свяжитесь с нами сегодня, чтобы узнать больше о наших продуктах и услугах!'
] */