import Head from "next/head"
import Image from "next/image"
import style from "../styles/Contacts.module.scss"
import React from 'react';
import { YMaps, Map, Placemark } from '@pbe/react-yandex-maps';

export default function Contacts() {
    const defaultState = {
        center: [56.395841, 41.317580],
        zoom: 11,
    };

    return(
        <div className="1">
            <Head>
                <title>Контакты</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className={style.adress}>
                <p>Наш адрес: <br />
                г. Ковров ул. Набережная, д. 23А, стр. 8</p>
                <div className={style.yaMap}>
                    <YMaps>
                        <Map defaultState={{
                            center: [56.395841, 41.317580],
                            zoom: 11, 
                            } }
                        >
                            <Placemark geometry={[56.395841, 41.317580]} />
                        </Map>
                    </YMaps>
                </div>
            </div>
            <div className={style.numbers}>
                <p>Телефоны: <br />
                    <span>8-930-031-00-53</span> <br />
                    <span>8-904-596-33-84</span> <br />
                </p> 
            </div>
            <div className={style.mail}>
                <p>stroidveri33@mail.ru</p>
            </div>
        </div>
    )
}