import Head from "next/head"

export default function Contacts() {
    return(
        <div className="1">
            <Head>
                <title>Контакты</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
        </div>
    )
}