import Head from "next/head"

export default function Delivery() {
    return(
        <>
            <Head>
                <title>Доставка</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
        </>
    )
}